config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  # Browser-based application routes
  mount Sidekiq::Web => '/sidekiq'

  root 'pages#root', as: :root

  # Devise
  devise_for :users,
             controllers: { registrations: 'users/registrations' },
             path: '',
             path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register', edit: 'profile' }

  # Resources (CRUD routes)
  resources :lists
  resources :colors
  resources :products do
    delete :delete_image_attachment, on: :member
  end
  resources :items
  resources :notifications

  # Other
  get 'dashboard' => 'pages#dashboard', as: :dashboard
  get 'up' => 'rails/health#show', as: :rails_health_check

  # ================================
  # API routes
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      # Devise
      devise_scope :user do
        # Sessions
        post 'login', to: 'users/sessions#create', as: :session_create
        delete 'logout', to: 'users/sessions#destroy', as: :session_destroy

        # Registrations
        post 'register', to: 'users/registrations#create', as: :user_registration_create        # Sign up
        patch 'profile', to: 'users/registrations#update', as: :user_registration_update        # Edit profile
        delete 'profile', to: 'users/registrations#destroy', as: :user_registration_destroy     # Delete profile

        # Passwords
        post 'password', to: 'devise/passwords#create', as: :user_password_create     # Reset password
        put 'password', to: 'devise/passwords#update', as: :user_password_update      # Change password
      end

      devise_for :users,
                 skip: %i[sessions registrations passwords],
                 controllers: { sessions: 'users/sessions', registrations: 'users/registrations' },
                 path: ''

      # Resources (CRUD routes)
      resources :lists, only: %i[index show create update destroy]
      resources :colors, only: %i[index show create update destroy]
      resources :products, only: %i[index show create update destroy] do
        delete 'image', to: 'products#delete_image_attachment', on: :member
      end
      resources :items, only: %i[index show create update destroy]
      resources :notifications, only: %i[index show create update destroy]

      # Other
      get 'current_user', to: 'current_user#show', as: :current_user
    end
  end
end

app/models/notification.rb
# frozen_string_literal: true

class Notification < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :items

  validates :days_before_expiration, presence: true, numericality: { only_integer: true, greater_than: 0 }
end

app/controllers/api/v1/notifications_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class NotificationsController < ApiController
      before_action :set_notification, only: %i[show update destroy]

      # GET /api/v1/notifications
      def index
        @notifications = current_user.notifications
      end

      # GET /api/v1/notifications/1
      def show; end

      # POST /api/v1/notifications
      def create
        @notification = Notification.new(notification_params)
        @notification.user_id = current_user.id

        if @notification.save
          render :show, status: :created
        else
          render json: { error: @notification.errors.full_messages }, status: :unprocessable_entity
        end
      end

      # PATCH/PUT /api/v1/notifications/1
      def update
        if @notification.update(notification_params)
          render :show, status: :ok
        else
          render json: { error: @notification.errors.full_messages }, status: :unprocessable_entity
        end
      end

      # DELETE /api/v1/notifications/1
      def destroy
        @notification.destroy!
        head :no_content
      end

      private

      # Use callbacks to share common setup or constraints between actions.
      def set_notification
        @notification = current_user.notifications.find_by_id(params[:id])
        render json: { error: 'Notification not found.' }, status: :not_found if @notification.nil?
      end

      # Only allow a list of trusted parameters through.
      def notification_params
        params.require(:notification).permit(:days_before_expiration)
      end
    end
  end
end

app/controllers/notifications_controller.rb
# frozen_string_literal: true

class NotificationsController < ApplicationController
  before_action :set_notification, only: %i[show edit update destroy]

  # GET /notifications
  def index
    @notifications = current_user.notifications
  end

  # GET /notifications/1
  def show; end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit; end

  # POST /notifications
  def create
    @notification = Notification.new(notification_params)
    @notification.user_id = current_user.id

    if @notification.save
      redirect_to notification_url(@notification), notice: 'Notification was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /notifications/1
  def update
    if @notification.update(notification_params)
      redirect_to notification_url(@notification), notice: 'Notification was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /notifications/1
  def destroy
    @notification.destroy!
    redirect_to notifications_url, notice: 'Notification was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_notification
    @notification = current_user.notifications.find_by_id(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def notification_params
    params.require(:notification).permit(:days_before_expiration)
  end
end

app/helpers/notifications_helper.rb
# frozen_string_literal: true

module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= form_with(model: notification) do |form| %>
  <% if notification.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
        <% notification.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :days_before_expiration, style: "display: block" %>
    <%= form.number_field :days_before_expiration %>
  </div>

  <div class="controls mt-2">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/notifications/_notification.html.erb
<div id="<%= dom_id notification %>">
  <p>
    <span class="font-semibold">Days before expiration:</span>
    <%= notification.days_before_expiration %>
  </p>
</div>

app/views/notifications/edit.html.erb
<h1>Editing notification</h1>

<%= render "form", notification: @notification %>

<div class="controls">
  <%= link_to "Show this notification", @notification, class: "btn btn-secondary" %>
  <%= link_to "Back to notifications", notifications_path, class: "btn btn-secondary" %>
</div>

app/views/notifications/index.html.erb
<h1>Notifications</h1>

<div id="notifications">
  <% @notifications.each do |notification| %>
    <div class="record-wrapper">
      <%= render notification %>

      <%= link_to notification, class: "icon-btn btn-secondary" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M2.036 12.322a1.012 1.012 0 0 1 0-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178Z" />
          <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
        </svg>
      <% end %>
    </div>
  <% end %>
</div>

<div class="controls mt-4">
  <%= link_to "New notification", new_notification_path, class: "btn btn-primary" %>
</div>

app/views/notifications/new.html.erb
<h1>New notification</h1>

<%= render "form", notification: @notification %>

<div class="controls">
  <%= link_to "Back to notifications", notifications_path, class: "btn btn-secondary" %>
</div>

app/views/notifications/show.html.erb
<div class="card">
  <%= render @notification %>
</div>

<div class="controls mt-4">
  <%= link_to "Edit this notification", edit_notification_path(@notification), class: "btn btn-primary" %>
  <%= link_to "Back to notifications", notifications_path, class: "btn btn-secondary" %>
  <%= button_to "Destroy this notification", @notification, method: :delete, class: "btn btn-danger" %>
</div>