config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  # Browser-based application routes
  mount Sidekiq::Web => '/sidekiq'

  root 'pages#root', as: :root

  # Devise
  devise_for :users,
             controllers: { registrations: 'users/registrations' },
             path: '',
             path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register', edit: 'profile' }

  # Resources (CRUD routes)
  resources :lists
  resources :colors
  resources :products do
    delete :delete_image_attachment, on: :member
  end
  resources :items
  resources :notifications

  # Other
  get 'dashboard' => 'pages#dashboard', as: :dashboard
  get 'up' => 'rails/health#show', as: :rails_health_check

  # ================================
  # API routes
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      # Devise
      devise_scope :user do
        # Sessions
        post 'login', to: 'users/sessions#create', as: :session_create
        delete 'logout', to: 'users/sessions#destroy', as: :session_destroy

        # Registrations
        post 'register', to: 'users/registrations#create', as: :user_registration_create        # Sign up
        patch 'profile', to: 'users/registrations#update', as: :user_registration_update        # Edit profile
        delete 'profile', to: 'users/registrations#destroy', as: :user_registration_destroy     # Delete profile

        # Passwords
        post 'password', to: 'devise/passwords#create', as: :user_password_create     # Reset password
        put 'password', to: 'devise/passwords#update', as: :user_password_update      # Change password
      end

      devise_for :users,
                 skip: %i[sessions registrations passwords],
                 controllers: { sessions: 'users/sessions', registrations: 'users/registrations' },
                 path: ''

      # Resources (CRUD routes)
      resources :lists, only: %i[index show create update destroy]
      resources :colors, only: %i[index show create update destroy]
      resources :products, only: %i[index show create update destroy] do
        delete 'image', to: 'products#delete_image_attachment', on: :member
      end
      resources :items, only: %i[index show create update destroy]
      resources :notifications, only: %i[index show create update destroy]

      # Other
      get 'current_user', to: 'current_user#show', as: :current_user
    end
  end
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  belongs_to :list
  belongs_to :user
  belongs_to :product
  has_and_belongs_to_many :notifications

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :expiration, allow_blank: true, comparison: { greater_than_or_equal_to: proc { Date.today } }

  def expired?
    return false if expiration.blank?
    return false if used?

    expiration < Date.today
  end
end

app/controllers/api/v1/items_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class ItemsController < ApiController
      before_action :set_item, only: %i[show update destroy]

      # GET /api/v1/items
      def index
        @items = current_user.items
      end

      # GET /api/v1/items/1
      def show; end

      # POST /api/v1/items
      def create
        @item = Item.new(item_params)
        @item.user_id = current_user.id

        if @item.save
          render :show, status: :created
        else
          render json: { error: @item.errors.full_messages }, status: :unprocessable_entity
        end
      end

      # PATCH/PUT /api/v1/items/1
      def update
        if @item.update(item_params)
          render :show, status: :ok
        else
          render json: { error: @item.errors.full_messages }, status: :unprocessable_entity
        end
      end

      # DELETE /api/v1/items/1
      def destroy
        @item.destroy!
        head :no_content
      end

      private

      # Use callbacks to share common setup or constraints between actions.
      def set_item
        @item = current_user.items.find_by_id(params[:id])
        render json: { error: 'Item not found.' }, status: :not_found if @item.nil?
      end

      # Only allow a list of trusted parameters through.
      def item_params
        params.require(:item).permit(:quantity, :expiration, :expired, :used, :product_id, :list_id,
                                     notifications_ids: [])
      end

      def schedule_expiration_notification
        return unless current_user.notify_through_email
        return unless @item.expiration
        return if @item.expired? || @item.used?

        @item.notifications.each do |notification|
          EmailExpirationNotificationJob.set(wait_until: @item.expiration - notification.days_before_expiration.days)
                                        .perform_later(current_user, @item, @item.expiration, notification)
        end
      end
    end
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  before_action :set_item, only: %i[show edit update destroy]
  after_action :schedule_expiration_notification, only: %i[create] # update is handled in the respective action

  # GET /items
  def index
    @items = current_user.items
  end

  # GET /items/1
  def show; end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit; end

  # POST /items
  def create
    @item = Item.new(item_params)
    @item.user_id = current_user.id

    if @item.save
      redirect_to item_url(@item), notice: 'Item was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /items/1
  def update
    params[:item][:notification_ids] = [] if item_params[:expiration].blank? || item_params[:used]

    current_notification_ids = @item.notification_ids

    if @item.update(item_params)
      if @item.previous_changes.key?('expiration') || (current_notification_ids != @item.notification_ids)
        schedule_expiration_notification
      end

      redirect_to item_url(@item), notice: 'Item was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /items/1
  def destroy
    @item.destroy!
    redirect_to items_url, notice: 'Item was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_item
    @item = current_user.items.find_by_id(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def item_params
    params.require(:item).permit(:quantity, :expiration, :expired, :list_id, :product_id, :used, notification_ids: [])
  end

  def schedule_expiration_notification
    return unless current_user.notify_through_email
    return unless @item.expiration
    return if @item.expired? || @item.used?

    @item.notifications.each do |notification|
      EmailExpirationNotificationJob.set(wait_until: @item.expiration - notification.days_before_expiration.days)
                                    .perform_later(current_user, @item, @item.expiration, notification)
    end
  end
end

app/helpers/items_helper.rb
# frozen_string_literal: true

module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.label :expiration, style: "display: block" %>
    <%= form.date_field :expiration, min: Date.today, id: "expiration_date_picker" %>
  </div>

  <div>
    <%= form.label :notification_ids, style: "display: block" %>
    <%= form.select :notification_ids, current_user.notifications.map { 
        |notification| ["#{pluralize(notification.days_before_expiration, "day")} before", notification.id] 
      }, { include_hidden: false, multiple: true }, id: "notification_select" %>
  </div>

  <div>
    <%= form.label :list_id, style: "display: block" %>
    <%= form.select :list_id, current_user.lists.map { |list| ["#{list.name}#{list.color.present? ? " (#{list.color&.hex_code})": ""}" , list.id] } %>
  </div>

  <div>
    <%= form.label :product_id, style: "display: block" %>
    <%= form.select :product_id, current_user.products.map { |product| ["#{product.name}" , product.id] } %>
  </div>

  <div class="controls mt-2">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

<script>
  document.addEventListener("turbo:load", function() {
    const expirationInput = document.getElementById('expiration_date_picker');
    const notificationSelect = document.getElementById('notification_select');

    function toggleNotificationSelect() {
      notificationSelect.disabled = !expirationInput.value;
    }

    toggleNotificationSelect();
    expirationInput.addEventListener("change", toggleNotificationSelect);
  });
</script>

app/views/items/_item.html.erb
<div id="<%= dom_id item %>">
  <p>
    <span class="font-semibold">Product:</span>
    <%= item.product.name %>
  </p>

  <p>
    <span class="font-semibold">Quantity:</span>
    <%= item.quantity %>
  </p>

  <p>
    <span class="font-semibold">Expiration:</span>
    <%= item.expiration&.to_date || "never" %>
  </p>

  <p>
    <span class="font-semibold">Expired:</span>
    <%= item.expired? %>
  </p>

  <p>
    <span class="font-semibold">Used:</span>
    <%= item.used? %>
  </p>

  <p>
    <span class="font-semibold">List:</span>
    <%= item.list.name %><% if item.list.color.present? %> (<span style="background-color: <%= item.list.color.hex_code %>; color: <%= contrast_color(item.list.color.hex_code) %>;"><%= item.list.color.hex_code %></span>)<% end %>
  </p>

  <p>
    <span class="font-semibold">Notifications:</span>
    <% if item.notifications.empty? %>
      none
    <% else %>
      <% item.notifications&.sort_by(&:days_before_expiration).each do |notification| %>
        <li>
          <%= notifications.days_before_expiration %> days before (<%= item.expiration&.to_date - notification.days_before_expiration.days %>)
        </li>
      <% end %>
    <% end %>
  </p>
</div>

app/views/items/_preview.html.erb
<div id="<%= dom_id item %>">
  <p>
    <span class="font-semibold">Product:</span>
    <%= item.product.name %>
  </p>

  <p>
    <span class="font-semibold">Quantity:</span>
    <%= item.quantity %>
  </p>

  <p>
    <span class="font-semibold">Expiration:</span>
    <%= item.expiration&.to_date || "never" %>
  </p>
</div>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render "form", item: @item %>

<div class="controls">
  <%= link_to "Show this item", @item, class: "btn btn-secondary" %>
  <%= link_to "Back to items", items_path, class: "btn btn-secondary" %>
</div>

app/views/items/index.html.erb
<h1>Items</h1>

<div id="items">
  <% @items.where(used: false).order(:expiration).each do |item| %>
    <div class="record-wrapper">
      <%= render item %>

      <div class="flex flex-col gap-2">
        <%= link_to item, class: "icon-btn btn-secondary", title: "View detail" do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M2.036 12.322a1.012 1.012 0 0 1 0-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178Z" />
            <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
          </svg>
        <% end %>

        <%= link_to item_path(item, item: { used: true }), class: "icon-btn btn-secondary", title: "Mark as used",
          data: { turbo_method: :patch } do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="m4.5 12.75 6 6 9-13.5" />
          </svg>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div class="controls mt-4">
  <%= link_to "New item", new_item_path, class: "btn btn-primary" %>
</div>

<h2 class="mt-8">Used items</h2>

<div id="used-items">
  <% @items.where(used: true).order(:expiration).each do |item| %>
    <div class="record-wrapper">
      <%= render item %>

      <div class="flex flex-col gap-2">
        <%= link_to item, class: "icon-btn btn-secondary", title: "View detail" do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M2.036 12.322a1.012 1.012 0 0 1 0-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178Z" />
            <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
          </svg>
        <% end %>

        <%= link_to item_path(item, item: { used: false }), class: "icon-btn btn-secondary", title: "Mark as not used",
          data: { turbo_method: :patch } do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
          </svg>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<h2 class="mt-8">Expired items</h2>

<div id="expired-items">
  <% @items.select(&:expired?).sort_by(&:expiration).each do |item| %>
    <div class="record-wrapper">
      <%= render item %>

      <%= link_to item, class: "icon-btn btn-secondary", title: "View detail" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M2.036 12.322a1.012 1.012 0 0 1 0-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178Z" />
          <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
        </svg>
      <% end %>
    </div>
  <% end %>
</div>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render "form", item: @item %>

<div class="controls">
  <%= link_to "Back to items", items_path, class: "btn btn-secondary" %>
</div>

app/views/items/show.html.erb
<div class="card">
  <%= render @item %>
</div>

<div class="controls mt-4 flex-col items-center">
  <div class="flex gap-2">
    <%= link_to "Edit this item", edit_item_path(@item), class: "btn btn-primary" %>
    <%= button_to "Destroy this item", @item, method: :delete, class: "btn btn-danger" %>
  </div>
  <% unless @item.expired? %>
    <div class="flex gap-2">
      <% if @item.used? %>
        <%= link_to "Mark as not used", item_path(@item, item: { used: false }), class: "btn btn-secondary", 
          data: { turbo_method: :patch } %>
      <% else %>
        <%= link_to "Mark as used", item_path(@item, item: { used: true }), class: "btn btn-secondary",
          data: { turbo_method: :patch } %>
      <% end %>

      <%= link_to "Back to items", items_path, class: "btn btn-secondary" %>
    </div>
  <% end %>  
</div>