config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  # Browser-based application routes
  mount Sidekiq::Web => '/sidekiq'

  root 'pages#root', as: :root

  # Devise
  devise_for :users,
             controllers: { registrations: 'users/registrations' },
             path: '',
             path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register', edit: 'profile' }

  # Resources (CRUD routes)
  resources :lists
  resources :colors
  resources :products do
    delete :delete_image_attachment, on: :member
  end
  resources :items
  resources :notifications

  # Other
  get 'dashboard' => 'pages#dashboard', as: :dashboard
  get 'up' => 'rails/health#show', as: :rails_health_check

  # ================================
  # API routes
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      # Devise
      devise_scope :user do
        # Sessions
        post 'login', to: 'users/sessions#create', as: :session_create
        delete 'logout', to: 'users/sessions#destroy', as: :session_destroy

        # Registrations
        post 'register', to: 'users/registrations#create', as: :user_registration_create        # Sign up
        patch 'profile', to: 'users/registrations#update', as: :user_registration_update        # Edit profile
        delete 'profile', to: 'users/registrations#destroy', as: :user_registration_destroy     # Delete profile

        # Passwords
        post 'password', to: 'devise/passwords#create', as: :user_password_create     # Reset password
        put 'password', to: 'devise/passwords#update', as: :user_password_update      # Change password
      end

      devise_for :users,
                 skip: %i[sessions registrations passwords],
                 controllers: { sessions: 'users/sessions', registrations: 'users/registrations' },
                 path: ''

      # Resources (CRUD routes)
      resources :lists, only: %i[index show create update destroy]
      resources :colors, only: %i[index show create update destroy]
      resources :products, only: %i[index show create update destroy] do
        delete 'image', to: 'products#delete_image_attachment', on: :member
      end
      resources :items, only: %i[index show create update destroy]
      resources :notifications, only: %i[index show create update destroy]

      # Other
      get 'current_user', to: 'current_user#show', as: :current_user
    end
  end
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  belongs_to :user
  has_many :items, dependent: :destroy
  has_one_attached :image

  validates :name, presence: true
  validates :barcode, presence: false, uniqueness: true, allow_blank: true
  validates :image, attached: false, content_type: ['image/png', 'image/jpg', 'image/jpeg'],
                    size: { less_than: 5.megabytes }, limit: { min: 0, max: 1 }
end

app/controllers/api/v1/products_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class ProductsController < ApiController
      before_action :set_product, only: %i[show update destroy delete_image_attachment]

      # GET /api/v1/products
      def index
        @products = current_user.products
      end

      # GET /api/v1/products/1
      def show; end

      # POST /api/v1/products
      def create
        @product = Product.new(product_params)
        @product.user_id = current_user.id

        if @product.save
          render :show, status: :created
        else
          render json: { error: @product.errors.full_messages }, status: :unprocessable_entity
        end
      end

      # PATCH/PUT /api/v1/products/1
      def update
        if @product.update(product_params)
          render :show, status: :ok
        else
          render json: { error: @product.errors.full_messages }, status: :unprocessable_entity
        end
      end

      # DELETE /api/v1/products/1
      def destroy
        @product.destroy!
        head :no_content
      end

      # DELETE /api/v1/products/1/image
      def delete_image_attachment
        @image = ActiveStorage::Blob.find_signed(params[:signed_id])
        return render json: { error: 'Image not found.' }, status: :not_found if @image.nil?

        @image.attachments.first.purge
        render status: :no_content
      end

      private

      # Use callbacks to share common setup or constraints between actions.
      def set_product
        @product = current_user.products.find_by_id(params[:id])
        render json: { error: 'Product not found.' }, status: :not_found if @product.nil?
      end

      # Only allow a list of trusted parameters through.
      def product_params
        params.require(:product).permit(:name, :barcode, :image)
      end
    end
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy delete_image_attachment]

  # GET /products
  def index
    @products = current_user.products
  end

  # GET /products/1
  def show; end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit; end

  # POST /products
  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id

    if @product.save
      redirect_to product_url(@product), notice: 'Product was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /products/1
  def update
    if @product.update(product_params)
      redirect_to product_url(@product), notice: 'Product was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /products/1
  def destroy
    @product.destroy!

    redirect_to products_url, notice: 'Product was successfully destroyed.'
  end

  def delete_image_attachment
    @image = ActiveStorage::Blob.find_signed(params[:signed_id])
    @image.attachments.first.purge

    redirect_to product_url(@product), notice: 'Image from the product was successfully removed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = current_user.products.find_by_id(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.require(:product).permit(:name, :barcode, :image)
  end
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :barcode, style: "display: block" %>
    <%= form.text_field :barcode %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <% if product.image.attached? %>
      <div class="flex flex-row gap-2 items-center">
        <%= image_tag product.image.representation(resize_to_fill: [50, 50]) %>
        <%= link_to delete_image_attachment_product_url(signed_id: product.image.signed_id), class: "icon-btn btn-danger",
          data: {
            turbo_method: :delete,
            turbo_confirm: "Are you sure?" 
          } do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" class="w-6 h-6 inline-block">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
          </svg>
        <% end %>
      </div>
      <%= product.image.filename %>

      <p class="text-danger-500 mt-2 mb-1">
        Uploading a new image will replace the existing one.
      </p>
    <% else %>
      <p>
        No image
      </p>
    <% end %>
    <%= form.file_field :image, accept: "image/png,image/jpg,image/jpeg" %>
  </div>

  <div class="controls mt-2">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <span class="font-semibold">Name:</span>
    <%= product.name %>
  </p>

  <p>
    <span class="font-semibold">Barcode:</span>
    <%= product.barcode %>
  </p>

  <p>
    <span class="font-semibold">Image:</span>
    <% if product.image.attached? %>
      <%= product.image.filename %>
      <%= link_to rails_blob_path(product.image, disposition: "inline"), target: "_blank" do %>
        <%= image_tag product.image.representation(resize_to_fill: [300, 300]) %>
      <% end %>
    <% else %>
      No image
    <% end %>
  </p>
</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<div class="controls">
  <%= link_to "Show this product", @product, class: "btn btn-secondary" %>
  <%= link_to "Back to products", products_path, class: "btn btn-secondary" %>
</div>

app/views/products/index.html.erb
<h1>Products</h1>

<div id="products">
  <% @products.each do |product| %>
    <div class="record-wrapper">
      <%= render product %>

      <%= link_to product, class: "icon-btn btn-secondary" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M2.036 12.322a1.012 1.012 0 0 1 0-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178Z" />
          <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
        </svg>
      <% end %>
    </div>
  <% end %>
</div>

<div class="controls mt-4">
  <%= link_to "New product", new_product_path, class: "btn btn-primary" %>
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<div class="controls">
  <%= link_to "Back to products", products_path, class: "btn btn-secondary" %>
</div>

app/views/products/show.html.erb
<div class="card">
  <%= render @product %>
</div>

<div class="controls mt-4">
  <%= link_to "Edit this product", edit_product_path(@product), class: "btn btn-primary" %>
  <%= link_to "Back to products", products_path, class: "btn btn-secondary" %>
  <%= button_to "Destroy this product", @product, method: :delete, class: "btn btn-danger" %>
</div>