config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  # Browser-based application routes
  mount Sidekiq::Web => '/sidekiq'

  root 'pages#root', as: :root

  # Devise
  devise_for :users,
             controllers: { registrations: 'users/registrations' },
             path: '',
             path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register', edit: 'profile' }

  # Resources (CRUD routes)
  resources :lists
  resources :colors
  resources :products do
    delete :delete_image_attachment, on: :member
  end
  resources :items
  resources :notifications

  # Other
  get 'dashboard' => 'pages#dashboard', as: :dashboard
  get 'up' => 'rails/health#show', as: :rails_health_check

  # ================================
  # API routes
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      # Devise
      devise_scope :user do
        # Sessions
        post 'login', to: 'users/sessions#create', as: :session_create
        delete 'logout', to: 'users/sessions#destroy', as: :session_destroy

        # Registrations
        post 'register', to: 'users/registrations#create', as: :user_registration_create        # Sign up
        patch 'profile', to: 'users/registrations#update', as: :user_registration_update        # Edit profile
        delete 'profile', to: 'users/registrations#destroy', as: :user_registration_destroy     # Delete profile

        # Passwords
        post 'password', to: 'devise/passwords#create', as: :user_password_create     # Reset password
        put 'password', to: 'devise/passwords#update', as: :user_password_update      # Change password
      end

      devise_for :users,
                 skip: %i[sessions registrations passwords],
                 controllers: { sessions: 'users/sessions', registrations: 'users/registrations' },
                 path: ''

      # Resources (CRUD routes)
      resources :lists, only: %i[index show create update destroy]
      resources :colors, only: %i[index show create update destroy]
      resources :products, only: %i[index show create update destroy] do
        delete 'image', to: 'products#delete_image_attachment', on: :member
      end
      resources :items, only: %i[index show create update destroy]
      resources :notifications, only: %i[index show create update destroy]

      # Other
      get 'current_user', to: 'current_user#show', as: :current_user
    end
  end
end

app/views/layouts/_flash.html.erb
<div>
  <% if notice.present? %>
    <p class="mt-2 p-2 border-2 border-primary-500 w-fit min-w-fit max-w-full mx-auto flex gap-1">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 inline-block ml-auto">
        <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 0 0 5.454-1.31A8.967 8.967 0 0 1 18 9.75V9A6 6 0 0 0 6 9v.75a8.967 8.967 0 0 1-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 0 1-5.714 0m5.714 0a3 3 0 1 1-5.714 0" />
      </svg>
      <span class="mr-auto"><%= notice %></span>
    </p>
  <% end %>
  <% if alert.present? %>
    <p class="mt-2 p-2 border-2 border-danger-500 min-w-fit max-w-full mx-auto flex gap-1">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 inline-block ml-auto">
        <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126ZM12 15.75h.007v.008H12v-.008Z" />
      </svg>
      <span class="mr-auto"><%= alert %></span>
    </p>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="bg-primary-500">
  <ul class="flex flex-row h-12 text-white">
    <% if user_signed_in? %>
      <li class="pl-4 mr-auto flex flex-row min-w-12">
        <%= link_to dashboard_path, title: "Dashboard" do %>
          <%= image_tag "stocked_shelves_icon_upscale_no_bg.png", alt: "StockedShelves logo", size: 48 %>
        <% end %>
      </li>
      <li class="flex flex-row items-center hover:bg-primary-600 transition-colors">
        <%= link_to "Items", items_path, class: "hover:underline hover:underline-offset-2 px-4" %>
      </li>
      <li class="flex flex-row items-center hover:bg-primary-600 transition-colors">
        <%= link_to "Products", products_path, class: "hover:underline hover:underline-offset-2 px-4 border-x border-x-primary-300 border-collapse" %>
      </li>
      <li class="flex flex-row items-center hover:bg-primary-600 transition-colors">
        <%= link_to "Lists", lists_path, class: "hover:underline hover:underline-offset-2 px-4" %>
      </li>
      <li class="flex flex-row items-center hover:bg-primary-600 transition-colors">
        <%= link_to "Colors", colors_path, class: "hover:underline hover:underline-offset-2 px-4 border-x border-x-primary-300 border-collapse" %>
      </li>
      <li class="flex flex-row items-center hover:bg-primary-600 transition-colors">
        <%= link_to "Notifications", notifications_path, class: "hover:underline hover:underline-offset-2 px-4" %>
      </li>
      <li class="ml-auto flex items-center hover:bg-primary-600 transition-colors">
        <%= link_to edit_user_registration_path, class: "flex flex-row gap-1 hover:underline hover:underline-offset-2 px-4 border-r border-r-primary-300 border-collapse" do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 inline-block">
            <path stroke-linecap="round" stroke-linejoin="round" d="M17.982 18.725A7.488 7.488 0 0 0 12 15.75a7.488 7.488 0 0 0-5.982 2.975m11.963 0a9 9 0 1 0-11.963 0m11.963 0A8.966 8.966 0 0 1 12 21a8.966 8.966 0 0 1-5.982-2.275M15 9.75a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
          </svg>
          <%= current_user.username %>
        <% end %>
      </li>
      <li class="flex flex-row items-center hover:bg-primary-600 transition-colors">
        <%= link_to "Log out", destroy_user_session_path, class: "hover:underline hover:underline-offset-2 px-4", data: {
          turbo_method: :delete
        } %>
      </li>
    <% else %>
      <li class="pl-4 mr-auto flex flex-row min-w-12">
        <%= link_to root_path, title: "Home" do %>
          <%= image_tag "stocked_shelves_icon_upscale_no_bg.png", alt: "StockedShelves logo", size: 48 %>
        <% end %>
      </li>
      <li class="flex flex-row items-center hover:bg-primary-600 transition-colors">
        <%= link_to "Log in", new_user_session_path, class: "hover:underline hover:underline-offset-2 px-4" %>
      </li>
      <li class="flex flex-row items-center hover:bg-primary-600 transition-colors">
        <%= link_to "Sign up", new_user_registration_path, class: "hover:underline hover:underline-offset-2 px-4" %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StockedShelves</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <%= render "layouts/navbar" %>
    </header>
  
    <%= render "layouts/flash" %>

    <main>
      <%= yield %>
    </main>
  </body>
</html>